In [1]:
import pandas as pd

darle tab a lo siguiente para ver opciones de ingreo de df

In [3]:
df = pd.read

AttributeError: module 'pandas' has no attribute 'read'

In [6]:
 # cargando un df con la navgaicon como en linux, si queremos cargar txt entonces usamos el delimiter, el encoding usarlo
# solo si no se carga bien
df = pd.read_csv("../../data/bodyfat.txt", delimiter = " ", decimal =".", encoding = "utf-8")

In [7]:
df

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
1,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
2,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
3,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
4,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
5,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,1.0736,11.0,70,134.25,67.00,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
249,1.0236,33.6,72,201.00,69.75,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
250,1.0328,29.3,72,186.75,66.00,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
251,1.0399,26.0,72,190.75,70.50,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
252,1.0271,31.9,74,207.50,70.00,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

In [8]:
# head, tail
df.head(8)

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
1,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
2,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
3,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
4,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
5,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
6,1.0502,20.9,24,210.25,74.75,39.0,104.5,94.4,107.8,66.0,42.0,25.6,35.7,30.6,18.8
7,1.0549,19.2,26,181.00,69.75,36.4,105.1,90.7,100.3,58.4,38.3,22.9,31.9,27.8,17.7
8,1.0704,12.4,25,176.00,72.50,37.8,99.6,88.5,97.1,60.0,39.4,23.2,30.5,29.0,18.8

In [26]:
df.tail(8)

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
245,1.0334,29.0,67,199.50,68.50,40.7,118.3,106.1,101.6,58.2,38.8,24.1,32.1,29.3,18.5
246,1.0641,15.2,68,155.50,69.25,36.3,97.4,84.3,94.4,54.3,37.5,22.6,29.2,27.3,18.5
247,1.0308,30.2,69,215.50,70.50,40.8,113.7,107.6,110.0,63.3,44.0,22.6,37.5,32.6,18.8
248,1.0736,11.0,70,134.25,67.00,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
249,1.0236,33.6,72,201.00,69.75,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
250,1.0328,29.3,72,186.75,66.00,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
251,1.0399,26.0,72,190.75,70.50,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
252,1.0271,31.9,74,207.50,70.00,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

In [28]:
#accediendo a renglones, en este caso empieza en 1, normalmente es en cero
df.loc[[1]]

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
1,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1

In [9]:
# por posicion, en este caso simepre empieza por 0, se puede proporiconar una lista
df.iloc[[1,3]]

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
2,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
4,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2

In [10]:
df[12:20]

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
13,1.0513,20.8,32,180.50,69.50,38.4,102.0,91.6,103.9,63.4,38.3,21.5,32.5,28.6,17.7
14,1.0505,21.2,30,205.25,71.25,39.4,104.1,101.8,108.6,66.0,41.5,23.7,36.9,31.6,18.8
15,1.0484,22.1,35,187.75,69.50,40.5,101.3,96.4,100.1,69.0,39.0,23.1,36.1,30.5,18.2
16,1.0512,20.9,35,162.75,66.00,36.4,99.1,92.8,99.2,63.1,38.7,21.7,31.1,26.4,16.9
17,1.0333,29.0,34,195.75,71.00,38.9,101.9,96.4,105.2,64.8,40.8,23.1,36.2,30.8,17.3
18,1.0468,22.9,32,209.25,71.00,42.1,107.6,97.5,107.0,66.9,40.0,24.4,38.2,31.6,19.3
19,1.0622,16.0,28,183.75,67.75,38.0,106.8,89.6,102.4,64.2,38.7,22.9,37.2,30.5,18.5
20,1.0610,16.5,33,211.75,73.50,40.0,106.2,100.5,109.0,65.8,40.6,24.0,37.1,30.1,18.2

In [11]:
 df[10:95:5]

,Density,Fat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
11,1.0830,7.1,26,186.25,74.50,38.5,101.5,83.6,98.2,59.7,39.7,25.2,32.8,29.4,18.5
16,1.0512,20.9,35,162.75,66.00,36.4,99.1,92.8,99.2,63.1,38.7,21.7,31.1,26.4,16.9
21,1.0551,19.1,28,179.00,68.00,39.1,103.3,95.9,104.9,63.5,38.0,22.1,32.5,30.3,18.4
26,1.0911,3.7,27,159.25,71.50,35.7,89.6,79.7,96.5,55.0,36.7,22.5,29.9,28.2,17.7
31,1.0716,11.9,32,182.00,73.75,38.7,100.5,88.7,99.8,57.5,38.7,33.9,32.5,27.7,18.4
36,1.0101,40.1,49,191.75,65.00,38.4,118.5,113.1,113.8,61.9,38.3,21.9,32.0,29.8,17.0
41,1.0217,34.5,45,262.75,68.75,43.2,128.3,126.2,125.6,72.5,39.6,26.6,36.4,32.7,21.4
46,1.0670,13.9,43,164.25,73.25,35.7,96.6,81.5,97.2,58.4,38.2,23.4,29.7,27.4,18.3
51,1.0756,10.2,47,158.25,72.25,34.9,90.2,86.7,98.3,52.6,37.2,22.4,26.0,25.8,17.3
56,1.0473,22.6,54,198.00,72.00,39.9,107.6,100.0,99.6,57.2,38.0,22.0,35.9,30.2,18.9
61,1.0396,26.1,62,216.00,73.25,41.4,112.3,104.8,103.1,61.6,40.9,23.1,36.2,31.8,20.2
66,1.0313,30.0,55,183.50,67.50,40.9,103.0,100.3,104.2,64.8,40.2,22.7,34.8,30.1,18.7
71,1.0439,24.3,62,167.50,71.50,35.5,97.6,91.5,98.5,56.6,38.6,22.4,31.5,27.3,18.6
76,1.0666,18.5,61,148.25,67.50,36.0,91.6,81.8,94.8,54.5,37.0,21.4,29.3,27.0,18.3
81,1.0283,31.4,67,163.75,67.75,38.4,97.7,95.8,97.1,54.8,38.2,23.7,29.4,27.2,19.0
86,1.0386,26.6,67,167.00,67.50,36.5,98.9,89.7,96.2,54.7,37.8,33.7,32.4,27.7,18.2
91,1.0520,20.5,46,177.00,70.00,37.2,99.7,95.6,102.2,58.3,38.2,22.5,29.1,27.7,17.7

In [12]:
#accediendo a las columas, variable
df.Density

1      1.0708
2      1.0853
3      1.0414
4      1.0751
5      1.0340
        ...
248    1.0736
249    1.0236
250    1.0328
251    1.0399
252    1.0271
Name: Density, Length: 252, dtype: float64

In [16]:
# operaciones en columnas
print(df.Density.sum())

266.0046

In [15]:
#para todas las columas
df.sum()

Density      266.0046
Fat         4826.0000
Age        11311.0000
Weight     45088.9500
Height     17677.5000
Neck        9574.0000
Chest      25407.7000
Abdomen    23324.1000
Hip        25176.0000
Thigh      14970.3000
Knee        9724.8000
Ankle       5821.8000
Biceps      8132.9000
Forearm     7223.3000
Wrist       4593.9000
dtype: float64

In [34]:
# transponer datos 
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Density,252.0,1.055574,0.019031,0.995,1.0414,1.0549,1.0704,1.1089
Fat,252.0,19.150794,8.368740,0.000,12.4750,19.2000,25.3000,47.5000
Age,252.0,44.884921,12.602040,22.000,35.7500,43.0000,54.0000,81.0000
Weight,252.0,178.924405,29.389160,118.500,159.0000,176.5000,197.0000,363.1500
Height,252.0,70.148810,3.662856,29.500,68.2500,70.0000,72.2500,77.7500
Neck,252.0,37.992063,2.430913,31.100,36.4000,38.0000,39.4250,51.2000
Chest,252.0,100.824206,8.430476,79.300,94.3500,99.6500,105.3750,136.2000
Abdomen,252.0,92.555952,10.783077,69.400,84.5750,90.9500,99.3250,148.1000
Hip,252.0,99.904762,7.164058,85.000,95.5000,99.3000,103.5250,147.7000
Thigh,252.0,59.405952,5.249952,47.200,56.0000,59.0000,62.3500,87.3000
Knee,252.0,38.590476,2.411805,33.000,36.9750,38.5000,39.9250,49.1000
Ankle,252.0,23.102381,1.694893,19.100,22.0000,22.8000,24.0000,33.9000
Biceps,252.0,32.273413,3.021274,24.800,30.2000,32.0500,34.3250,45.0000
Forearm,252.0,28.663889,2.020691,21.000,27.3000,28.7000,30.0000,34.9000
Wrist,252.0,18.229762,0.933585,15.800,17.6000,18.3000,18.8000,21.4000

In [17]:
# tamaÃ±o filas, columnas
df.shape

(252, 15)

In [18]:
# importando desde internet
df2 = pd.read_csv("http:....")

URLError: <urlopen error no host given>